# Generated by Django 4.2.11 on 2026-05-10 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('academic', 'Academic Building'), ('admin', 'Administration'), ('library', 'Library'), ('medical', 'Medical / Health'), ('security', 'Security'), ('sports', 'Sports & Recreation'), ('food', 'Food & Cafeteria'), ('religious', 'Religious'), ('transport', 'Transport'), ('hostel', 'Hostel / Residence'), ('lab', 'Laboratory'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('building_code', models.CharField(blank=True, max_length=20)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('college', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campus_locations',
                'ordering': ['category', 'name'],
            },
        ),
    ]
