# Generated by Django 4.2.11 on 2026-05-19 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('search_query', models.CharField(blank=True, max_length=300)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to='campus.campuslocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'location_search_history',
                'ordering': ['-searched_at'],
            },
        ),
    ]
