# Generated by Django 4.2.11 on 2026-05-10 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('deadline_date', models.DateTimeField()),
                ('course', models.CharField(blank=True, max_length=200)),
                ('college', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('assignment', 'Assignment'), ('exam', 'Exam'), ('registration', 'Registration'), ('project', 'Project / FYP'), ('fee', 'Fee Payment'), ('application', 'Application'), ('other', 'Other')], default='other', max_length=20)),
                ('target_roles', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deadlines',
                'ordering': ['deadline_date'],
            },
        ),
        migrations.CreateModel(
            name='AlmanacEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('semester_start', 'Semester Start'), ('semester_end', 'Semester End'), ('exam_period', 'Exam Period'), ('holiday', 'Public Holiday'), ('registration', 'Registration Period'), ('graduation', 'Graduation'), ('orientation', 'Orientation'), ('sports', 'Sports Week'), ('other', 'Other')], max_length=20)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('college', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almanac_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'almanac_events',
                'ordering': ['start_date'],
            },
        ),
    ]
