# Generated by Django 4.2.11 on 2026-05-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Medical', 'Medical'), ('Security', 'Security'), ('Fire', 'Fire'), ('Counseling', 'Counseling')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('priority', models.IntegerField(default=1)),
                ('visible_to', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'emergency_contacts',
                'ordering': ['priority'],
            },
        ),
    ]
