# Generated by Django 4.2.11 on 2026-05-10 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('workshop', 'Workshop'), ('seminar', 'Seminar'), ('conference', 'Conference'), ('webinar', 'Webinar')], max_length=20)),
                ('organizer', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.CharField(blank=True, max_length=10)),
                ('max_attendees', models.IntegerField()),
                ('registration_link', models.URLField(blank=True)),
                ('college', models.JSONField(blank=True, default=list)),
                ('department', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('target_roles', models.JSONField(default=list)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='events.event')),
            ],
            options={
                'db_table': 'event_media',
            },
        ),
    ]
