# Generated by Django 4.2.11 on 2026-05-19 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_announcements', models.BooleanField(default=True)),
                ('show_events', models.BooleanField(default=True)),
                ('show_quick_links', models.BooleanField(default=True)),
                ('layout_type', models.CharField(choices=[('grid', 'Grid'), ('list', 'List')], default='grid', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_preferences',
            },
        ),
    ]
