# Generated by Django 4.2.11 on 2026-05-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('target_roles', models.JSONField(default=list)),
                ('college', models.JSONField(default=list)),
                ('location_coordinates', models.JSONField(blank=True, null=True)),
                ('location_radius', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('emergency', 'Emergency'), ('academic', 'Academic'), ('general', 'General'), ('opportunity', 'Opportunity'), ('event', 'Event')], default='general', max_length=20)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('is_published', models.BooleanField(default=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
