# Generated by Django 4.2.11 on 2026-05-10 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('sports', 'Sports'), ('technology', 'Technology'), ('health', 'Health'), ('academics', 'Academics'), ('alumni', 'Alumni'), ('students_life', "Students' Life"), ('career_fair', 'Career Fair')], max_length=30)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('target_roles', models.JSONField(default=list)),
                ('college', models.JSONField(default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'news',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='news.news')),
            ],
            options={
                'db_table': 'news_media',
            },
        ),
    ]
