# Generated by Django 4.2.11 on 2026-05-19 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('alumni_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_initiated', to='alumni.alumniprofile')),
                ('alumni_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_received', to='alumni.alumniprofile')),
            ],
            options={
                'db_table': 'alumni_connections',
                'unique_together': {('alumni_1', 'alumni_2')},
            },
        ),
    ]
