# Generated by Django 4.2.11 on 2026-05-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('source_type', models.CharField(choices=[('announcement', 'Announcement'), ('news', 'News'), ('event', 'Event'), ('mentorship', 'Mentorship'), ('admin_action', 'Admin Action'), ('general', 'General')], max_length=30)),
                ('source_id', models.CharField(max_length=50)),
                ('seen', models.BooleanField(default=False)),
                ('delivered_via', models.JSONField(default=list)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-sent_at'],
            },
        ),
    ]
