# Generated by Django 4.2.11 on 2026-05-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, choices=[('college_admin', 'College Admin'), ('system_admin', 'System Admin'), ('student', 'Student'), ('alumni', 'Alumni')], max_length=20)),
                ('target_resource', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
